name: Pre-Release
on:
  push:
    branches:
      - main
    paths-ignore:
        - 'RELEASING.md'
        - 'README.md'
jobs:
    pre-release:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0 
    
        - name: Version
          uses: paulhatch/semantic-version@v5.4.0
          id: version
          with:
            tag_prefix: ""
                
        - name: Update SDK Version 
          run: |
            sed -i "s/\$JOURNIFY_VERSION = '.*';/\$JOURNIFY_VERSION = '${{ steps.version.outputs.version_tag }}';/" lib/Version.php 
        
        - uses: stefanzweifel/git-auto-commit-action@v5
          with:
             branch: pre-release-${{ steps.version.outputs.version_tag }}
             create_branch: true
        
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v7
          with:
            title: "chore(pre-release): ${{ steps.version.outputs.version_tag }}"
            body: "This PR updates the version to `${{ steps.version.outputs.version_tag }}` on version.php file"
            base: main
            branch: pre-release-${{ steps.version.outputs.version_tag }}


